#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Ryota Ema <rhenium4694@gmail.com>
#SPDX-License-Identifier: BSD-3-Clause

#平均のプログラム
import sys
import math

ave = 0.0
ans = 0.0
count = 0

for line in sys.stdin:
    try:
        num = float(line)
        ans += num
        count += 1
    except ValueError:
        pass

ave = ans / count
print(ave)
