#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Ryota Ema <rhenium4694@gmail.com>  
#SPDX-License-Identifier: BSD-3-Clause

#階乗の計算
import sys
import math

ans = 0
i = 0


try:
    #num = int(sys.stdin.readline)
    num = int(sys.argv[1])
    ans = 1
    for i in range(1,num + 1):
        ans *= i
    print(ans)
except ValueError:
    print("「整数」を入力してください")
